-- Tables pour les données Cholera
CREATE TABLE IF NOT EXISTS cholera_cas (
    id SERIAL PRIMARY KEY,
    provenance TEXT,
    n_epid_prov TEXT,
    n_epid TEXT,
    statut_a_l_arrivee TEXT,
    date_arrivee_malade DATE,
    date_admission DATE,
    date_notification DATE,
    date_investigation DATE,
    date_debut_maladie DATE,
    province_notification TEXT,
    zone_de_sante_notification TEXT,
    aire_de_sante_notification TEXT,
    semaine_epid TEXT,
    num_semaine_epi INTEGER,
    annee_epi INTEGER,
    nom_complet TEXT,
    sexe TEXT,
    age_annee FLOAT,
    age_mois FLOAT,
    age FLOAT,
    unite_age TEXT,
    tranche_age TEXT,
    tranche_age_en_ans TEXT,
    profession TEXT,
    province_provenance TEXT,
    zone_de_sante_provenance TEXT,
    aire_de_sante_provenance TEXT,
    adresse TEXT,
    symptomes TEXT,
    prise_antibiotique_avant_admission TEXT,
    nom_antibiotique TEXT,
    antecedents_morbides TEXT,
    femme_enceinte TEXT,
    degre_deshydratation TEXT,
    plan_de_deshydratation TEXT,
    hospitalisation TEXT,
    prelevement TEXT,
    date_prelevement DATE,
    tdr_realise TEXT,
    tdr_resultat TEXT,
    resultat_labo TEXT,
    resultat_labo_culture TEXT,
    serotype TEXT,
    nom_structure_realisant_le_tdr TEXT,
    resultat_labo_pcr TEXT,
    traitement_antibiotique TEXT,
    quantite_total_ringer_recue FLOAT,
    quantite_total_sro_recue FLOAT,
    ctc_utc TEXT,
    issue TEXT,
    date_de_sortie_malade DATE,
    etat_sortie_malade TEXT,
    statut_vaccinal TEXT,
    nombre_dose INTEGER,
    annee_vaccination INTEGER,
    source_eventuelle_de_contamination TEXT,
    source_approvisionnement_en_eau TEXT,
    classification_finale TEXT,
    date_de_guerie DATE,
    observation TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_cholera_province ON cholera_cas(province_notification);
CREATE INDEX IF NOT EXISTS idx_cholera_semaine ON cholera_cas(num_semaine_epi, annee_epi);
CREATE INDEX IF NOT EXISTS idx_cholera_date_admission ON cholera_cas(date_admission);
CREATE INDEX IF NOT EXISTS idx_cholera_classification ON cholera_cas(classification_finale);